const ShopActionTypes = {
    //UPDATE_COLLECTIONS: ' UPDATE_COLLECTIONS'
    FETCH_COLLECTIONS_START: 'FETCH_COLLECTIONS_START',
    FETCH_COLLECTIONS_SUCCSESS: 'FETCH_COLLECTIONS_SUCCSESS',
    FETCH_COLLECTIONS_FAILURE: 'FETCH_COLLECTIONS_FAILURE'
}

export default ShopActionTypes;